######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 20 20:21:12 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += invertwidget.h mainwindow.h
SOURCES += invertwidget.cpp main.cpp mainwindow.cpp
