######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 11 15:44:27 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . debug
INCLUDEPATH += .

# Input
HEADERS += imagewidget.h mainwindow.h
SOURCES += imagewidget.cpp main.cpp mainwindow.cpp
RESOURCES += application.qrc
