######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 10 14:34:16 2007
######################################################################

TEMPLATE = app
QT += opengl
TARGET = openglRotate
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mygl.h
SOURCES += main.cpp mygl.cpp
