######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 29 22:28:21 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TestWidget.h
FORMS += test.ui
SOURCES += main.cpp TestWidget.cpp
RESOURCES += test.qrc
