# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/timeserver
QT  += network
HEADERS += timethread.h \
           timeserver.h \
           dialog.h 
SOURCES += timethread.cpp \
           timeserver.cpp \
           main.cpp \
           dialog.cpp 
TARGET=../bin/timeserver
