######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 13 11:38:57 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywidget.h
SOURCES += main.cpp mywidget.cpp
