# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/mouseevent

HEADERS += mainwindow.h \
           drawarea.h 
SOURCES += mainwindow.cpp \
           main.cpp \
           drawarea.cpp 
TARGET=../bin/mouseevent
