# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/codemainwindow

HEADERS += mainwindow.h 
SOURCES += codemainwindow.cpp \
           mainwindow.cpp 
TARGET=../bin/codemainwindow
			RESOURCES += ./images/mainwindow.qrc
