######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 25 19:53:02 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tablemodel.h
SOURCES += main.cpp tablemodel.cpp
