# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/direct

FORMS += ../../findfileform.ui 
SOURCES += direct.cpp 
TARGET=../bin/direct
RESOURCES    += ../../findfile.qrc
