# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/timeclient
QT      += network
HEADERS += client.h 
SOURCES += main.cpp \
           client.cpp 
TARGET=../bin/timeclient
