######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 4 10:34:31 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . debug release
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h testwidget.h
SOURCES += main.cpp mainwindow.cpp testwidget.cpp
RESOURCES += toolbar.qrc
