######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 11 17:18:24 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DirWidget.h
SOURCES += DirWidget.cpp main.cpp
