# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/sqlbrowser
QT += sql
FORMS += qsqlconnectiondialog.ui 
HEADERS += qsqlconnectiondialog.h 
SOURCES += qsqlconnectiondialog.cpp \
           main.cpp 
TARGET=../bin/sqlbrowser
