######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 30 11:26:36 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
