######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 16 11:05:20 2007
######################################################################

TEMPLATE = app
QT += opengl
TARGET = opengl3D
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mygl.h
SOURCES += main.cpp mygl.cpp
