######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 27 09:42:49 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . debug
INCLUDEPATH += .

# Input
HEADERS += radar.h target.h mainwindow.h
SOURCES += main.cpp radar.cpp target.cpp mainwindow.cpp
RESOURCES += map.qrc radar.qrc
