######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 10 18:27:12 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . debug
INCLUDEPATH += .

# Input
HEADERS += commands.h mainwindow.h undowidget.h
SOURCES += commands.cpp main.cpp mainwindow.cpp undowidget.cpp
RESOURCES += undo.qrc
