######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 27 17:32:29 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h radar.h target.h
SOURCES += main.cpp mainwindow.cpp radar.cpp target.cpp
RESOURCES += c2.qrc
