######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 22 19:13:23 2007
######################################################################

TEMPLATE = app
QT += xml
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
