######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 22 11:21:06 2007
######################################################################

TEMPLATE = app
CONFIG += uitools
QT += script
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += rtfedit.h
FORMS += rtfedit.ui
SOURCES += main.cpp rtfedit.cpp
RESOURCES += rtfedit.qrc
