######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 20 17:26:40 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += arrowwidget.h mainwindow.h
SOURCES += arrowwidget.cpp main.cpp mainwindow.cpp
