######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 7 08:52:52 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += GUI

# Input
HEADERS += target.h \
radar.h
SOURCES += main.cpp target.cpp \
radar.cpp
RESOURCES += map.qrc
