######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 16 21:41:02 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ConvertWidget.h
FORMS += convert.ui
SOURCES += ConvertWidget.cpp main.cpp
