# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/udpreceiver

HEADERS += receiver.h 
SOURCES += main.cpp \
           receiver.cpp 
QT +=network
TARGET=../bin/udpreceiver
