######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 7 22:12:31 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mysortfilterproxymodel.h score.h
FORMS += score.ui
SOURCES += main.cpp mysortfilterproxymodel.cpp score.cpp
