######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 8 21:39:55 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dndwidget.h
SOURCES += dndwidget.cpp main.cpp
