# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/ftplogin
QT +=network
HEADERS += ftplogin.h 
SOURCES += ftplogin.cpp \
           main.cpp 
TEMPLATE = app
CONFIG += release \
warn_on \
thread \
qt
TARGET = ../bin/ftplogin
