######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 15 17:58:26 2007
######################################################################

TEMPLATE = app
CONFIG += qtestlib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += guireplay.cpp
