######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 21 14:59:13 2007
######################################################################

TEMPLATE = app
CONFIG += uitools
QT += script
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += table.ui
SOURCES += main.cpp
RESOURCES += table.qrc
