# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/mydialog

HEADERS += logindlg.h 
SOURCES += mydialog.cpp \
           logindlg.cpp 
TARGET=../bin/mydialog
