######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 10 10:47:41 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += weaponmodel.h
SOURCES += main.cpp weaponmodel.cpp
