# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/carinfo
QT += sql 
SOURCES += sqlite.cpp 
TARGET=../bin/carinfo
