######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 9 20:42:50 2007
######################################################################

TEMPLATE = app
QT += xml
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h drawwidget.h
SOURCES += main.cpp mainwindow.cpp drawwidget.cpp

