######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 10 16:03:00 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
