# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/property

HEADERS += weapon.h 
SOURCES += property.cpp \
           weapon.cpp 
TARGET=../bin/property
