######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 18 21:04:04 2007
######################################################################

TEMPLATE = app
QT += script
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
