######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 14 16:50:44 2007
######################################################################

TEMPLATE = app
CONFIG += qtestlib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += nautical.h
SOURCES += nautical.cpp testdata.cpp
