######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 8 20:01:43 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
