# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/car_factory

FORMS += connectdlg.ui 
HEADERS += mainwindow.h \
           editdialog.h \
           connectdlg.h 
SOURCES += mainwindow.cpp \
           main.cpp \
           editdialog.cpp \
           connectdlg.cpp 
TARGET=../bin/car_factory
QT += sql
QT += xml
