# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/receivefile

HEADERS += dialog.h 
SOURCES += main.cpp \
           dialog.cpp 
TARGET=../bin/receivefile
QT += network
CONFIG +=debug
