# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/mdiarea

FORMS += findfileform.ui \
         mainwindow.ui 
HEADERS += findfileform.h \
           mainwindow.h \
           mditextedit.h 
SOURCES += mdiarea.cpp \
           findfileform.cpp \
           mainwindow.cpp \
           mditextedit.cpp 
TARGET=../bin/mdiarea
RESOURCES += images/mainwindow.qrc
