# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/wget
QT +=network
HEADERS += httpget.h 
SOURCES += httpget.cpp \
           main.cpp 
TEMPLATE = app
CONFIG += release \
warn_on \
thread \
qt
TARGET = ../bin/wget
