# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/semaphores

SOURCES += semaphores.cpp 
TARGET=../bin/semaphores
