# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/designmainwindow

FORMS += mainwindow.ui \
         findfileform.ui 
HEADERS += mainwindow.h \
           findfileform.h 
SOURCES += designmainwindow.cpp \
           mainwindow.cpp \
           findfileform.cpp 
TARGET=../bin/designmainwindow
RESOURCES += images/mainwindow.qrc
