# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/builtin

HEADERS += builtindlg.h 
SOURCES += builtin.cpp \
           builtindlg.cpp 
TARGET=../bin/builtin
