######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 30 08:26:42 2007
######################################################################

TEMPLATE = app
QT += opengl
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mygl.h
SOURCES += main.cpp mygl.cpp
