# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/eventfilter


QT       += core gui
CONFIG += thread

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets



HEADERS += digitdialog.h \
           button.h 
SOURCES += main.cpp \
           digitdialog.cpp \
           button.cpp 
TARGET=../bin/eventfilter
