# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/layout

FORMS += layoutdlg.ui 
HEADERS += layoutdlg.h 
SOURCES += layout.cpp \
           layoutdlg.cpp 
TARGET=../bin/layout
