######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 2 06:58:56 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
