# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/socket

HEADERS += CBase.h \
           GroupServer.h 
SOURCES += GroupServer.cpp \
           main.cpp 
TARGET = ../bin/socket
CONFIG += release \
warn_on \
qt \
thread
TEMPLATE = app
QT += network
