######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 11 09:51:58 2007
######################################################################

TEMPLATE = app
QT += svg
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
