######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 2 21:09:58 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
