# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/sendfile

HEADERS += dialog.h 
SOURCES += main.cpp \
           dialog.cpp 
TARGET=../bin/sendfile
QT +=network
CONFIG +=debug
