# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/startThread

HEADERS += workThread.h \
           dialog.h 
SOURCES += workThread.cpp \
           main.cpp \
           dialog.cpp 
TARGET=../bin/startThread
QT +=network
CONFIG +=debug
