######################################################################
# Automatically generated by qmake (2.01a) ??? ??? 15 19:54:36 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
HEADERS += src/dialog.h
SOURCES += src/dialog.cpp src/main.cpp
