######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 7 21:48:00 2007
######################################################################

TEMPLATE = app
CONFIG += qtestlib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += nautical.h
SOURCES += testnautical.cpp
