######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 16 11:27:36 2007
######################################################################

TEMPLATE = app
QT += opengl
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mygl.h
SOURCES += main.cpp mygl.cpp
RESOURCES += texture.qrc
