######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 1 09:34:50 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += composition.h
SOURCES += composition.cpp main.cpp
