# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/geometry

FORMS += ctrlform.ui 
HEADERS += ctrlform.h 
SOURCES += geometry.cpp \
           ctrlform.cpp 
TARGET=../bin/geometry
