# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/udpsender

HEADERS += sender.h 
SOURCES += main.cpp \
           sender.cpp 
QT +=network
TARGET=../bin/udpsender
