######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 24 17:05:10 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
