# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/waitconditions

SOURCES += waitconditions.cpp 
TARGET=../bin/waitconditions
