# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/singleinherit

FORMS += ../../findfileform.ui 
HEADERS += findfileform.h 
SOURCES += singleinherit.cpp \
           findfileform.cpp 
TARGET=../bin/singleinherit
RESOURCES +=../../findfile.qrc
