# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./loadcalculate/calculate
# Target is ????? 

CONFIG += debug \
          warn_on \
		  qdbus
TEMPLATE = app 
HEADERS += calculate_adaptor.h \
           calculate.h 
SOURCES += calculate_adaptor.cpp \
           calculate.cpp \
           main.cpp 
