######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 17 22:23:21 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += UniCodeWidget.h
SOURCES += main.cpp UniCodeWidget.cpp
