# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/mulinherit

FORMS += ../../findfileform.ui 
HEADERS += findfileform.h 
SOURCES += mulinherit.cpp \
           findfileform.cpp 
TARGET=../bin/mulinherit
RESOURCES +=../../findfile.qrc
