######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 2 16:13:44 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
