######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 7 08:50:01 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qsql_occi.h
SOURCES += QOCCIDriverPlugin.cpp qsql_occi.cpp
