######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 8 15:52:03 2007
######################################################################

TEMPLATE = app
QT += xml
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += highlighter.h mainwindow.h uireader.h
SOURCES += highlighter.cpp main.cpp mainwindow.cpp uireader.cpp
