# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/workspace

FORMS += mainwindow.ui \
         findfileform.ui 
HEADERS += mditextedit.h \
           mainwindow.h \
           findfileform.h 
SOURCES += workspace.cpp \
           mditextedit.cpp \
           mainwindow.cpp \
           findfileform.cpp 
TARGET=../bin/workspace
RESOURCES += images/mainwindow.qrc
