######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 26 09:11:35 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += CapMain.cpp
