######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 7 18:12:35 2007
######################################################################

TEMPLATE = app
QT += xml
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h uihandler.h \
highlighter.h
SOURCES += main.cpp mainwindow.cpp uihandler.cpp \
highlighter.cpp
