######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 8 20:08:12 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . debug
INCLUDEPATH += .

# Input
HEADERS += mapdelegate.h mapwidget.h
SOURCES += main.cpp mapdelegate.cpp mapwidget.cpp
RESOURCES += flags.qrc
