######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 6 21:55:09 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += delegate.h
SOURCES += delegate.cpp main.cpp
