######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 2 19:51:03 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Msg.h
SOURCES += main.cpp Msg.cpp
