######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 15 15:12:57 2007
######################################################################

TEMPLATE = app
CONFIG += qtestlib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += guitest.cpp
