######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 2 16:47:28 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
