# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./loadcalculate/show
# Target is ????? show

FORMS += loadform.ui 
HEADERS += loadform.h \
           calculate_interface.h 
SOURCES += main.cpp \
           loadform.cpp \
           calculate_interface.cpp 
TARGET = show
DESTDIR = .
CONFIG += debug \
warn_on \
qdbus
TEMPLATE = app
