######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 6 10:42:47 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp 
